/**
 * Human-readable descriptions for common NAICS and PSC codes.
 * Not exhaustive — returns the code itself if no description found.
 */

const NAICS: Record<string, string> = {
  "111110": "Soybean Farming",
  "236220": "Commercial & Institutional Building Construction",
  "237310": "Highway, Street, and Bridge Construction",
  "238210": "Electrical Contractors",
  "311999": "All Other Miscellaneous Food Manufacturing",
  "332510": "Hardware Manufacturing",
  "332994": "Small Arms, Ordnance, and Ordnance Accessories Manufacturing",
  "333120": "Construction Machinery Manufacturing",
  "333415": "AC, Refrigeration, and Warm Air Heating Equipment Manufacturing",
  "334111": "Electronic Computer Manufacturing",
  "334290": "Other Communications Equipment Manufacturing",
  "334511": "Search, Detection, Navigation, and Aeronautical Systems Manufacturing",
  "334516": "Analytical Laboratory Instrument Manufacturing",
  "335999": "All Other Miscellaneous Electrical Equipment Manufacturing",
  "336110": "Automobile and Light Duty Motor Vehicle Manufacturing",
  "336411": "Aircraft Manufacturing",
  "336413": "Other Aircraft Parts and Auxiliary Equipment Manufacturing",
  "336414": "Guided Missile and Space Vehicle Manufacturing",
  "336611": "Ship Building and Repairing",
  "337127": "Institutional Furniture Manufacturing",
  "339113": "Surgical Appliance and Supplies Manufacturing",
  "423450": "Medical, Dental, and Hospital Equipment Merchant Wholesalers",
  "488190": "Other Support Activities for Air Transportation",
  "511210": "Software Publishers",
  "517111": "Wired Telecommunications Carriers",
  "517312": "Wireless Telecommunications Carriers",
  "518210": "Data Processing, Hosting, and Related Services",
  "519130": "Internet Publishing and Broadcasting",
  "519190": "All Other Information Services",
  "541330": "Engineering Services",
  "541380": "Testing Laboratories and Services",
  "541511": "Custom Computer Programming Services",
  "541512": "Computer Systems Design Services",
  "541513": "Computer Facilities Management Services",
  "541519": "Other Computer Related Services",
  "541611": "Administrative Management Consulting Services",
  "541612": "Human Resources Consulting Services",
  "541613": "Marketing Consulting Services",
  "541614": "Process, Physical Distribution, and Logistics Consulting",
  "541618": "Other Management Consulting Services",
  "541690": "Other Scientific and Technical Consulting Services",
  "541715": "R&D in the Physical, Engineering, and Life Sciences",
  "541990": "All Other Professional, Scientific, and Technical Services",
  "561110": "Office Administrative Services",
  "561210": "Facilities Support Services",
  "561320": "Temporary Help Services",
  "561612": "Security Guards and Patrol Services",
  "561621": "Security Systems Services",
  "561710": "Exterminating and Pest Control Services",
  "561720": "Janitorial Services",
  "561730": "Landscaping Services",
  "611430": "Professional and Management Development Training",
  "621999": "All Other Miscellaneous Ambulatory Health Care Services",
  "811310": "Commercial Machinery Repair and Maintenance",
  "928110": "National Security",
};

/**
 * PSC codes can be 2-character groups or 4-character specific codes.
 * We store both for flexible lookup.
 */
const PSC: Record<string, string> = {
  // Services (letter prefixes)
  "A": "R&D - Agriculture/Forestry/Fishing",
  "B": "Special Studies and Analyses",
  "C": "Architect and Engineering Services",
  "D": "ADP and Telecommunications Services",
  "E": "Purchase of Structures and Facilities",
  "F": "Natural Resources and Conservation",
  "G": "Social Services",
  "H": "Quality Control, Testing, and Inspection",
  "J": "Maintenance, Repair, and Rebuilding of Equipment",
  "K": "Modification of Equipment",
  "L": "Technical Representative Services",
  "M": "Operation of Structures and Facilities",
  "N": "Installation of Equipment",
  "P": "Salvage Services",
  "Q": "Medical Services",
  "R": "Professional, Administrative, and Management Support",
  "S": "Utilities and Housekeeping Services",
  "T": "Photographic, Mapping, Printing Services",
  "U": "Education and Training Services",
  "V": "Transportation, Travel, and Relocation",
  "W": "Lease or Rental of Equipment",
  "X": "Lease or Rental of Facilities",
  "Y": "Construction of Structures and Facilities",
  "Z": "Maintenance, Repair, or Alteration of Real Property",
  // Products (numeric prefixes)
  "10": "Weapons",
  "11": "Nuclear Ordnance",
  "12": "Fire Control Equipment",
  "13": "Ammunition and Explosives",
  "14": "Guided Missiles",
  "15": "Aircraft and Airframe Structural Components",
  "16": "Aircraft Components and Accessories",
  "17": "Aircraft Launch/Landing/Ground Handling Equipment",
  "19": "Ships, Small Craft, Pontoons, and Floating Docks",
  "20": "Ship and Marine Equipment",
  "22": "Railway Equipment",
  "23": "Ground Effect Vehicles and Motor Vehicles",
  "24": "Tractors",
  "25": "Vehicular Equipment Components",
  "26": "Tires and Tubes",
  "28": "Engines, Turbines, and Components",
  "29": "Engine Accessories",
  "30": "Mechanical Power Transmission Equipment",
  "31": "Bearings",
  "32": "Woodworking Machinery and Equipment",
  "34": "Metalworking Machinery",
  "35": "Service and Trade Equipment",
  "36": "Special Industry Machinery",
  "37": "Agricultural Machinery and Equipment",
  "38": "Construction, Mining, Excavating Equipment",
  "39": "Materials Handling Equipment",
  "40": "Rope, Cable, Chain, and Fittings",
  "41": "Refrigeration, AC, and Air Circulating Equipment",
  "42": "Fire Fighting, Rescue, and Safety Equipment",
  "43": "Pumps and Compressors",
  "44": "Furnace, Steam, Drying, and Nuclear Reactor Equipment",
  "45": "Plumbing, Heating, and Waste Disposal Equipment",
  "46": "Water Purification and Sewage Treatment Equipment",
  "47": "Pipe, Tubing, Hose, and Fittings",
  "48": "Valves",
  "49": "Maintenance and Repair Shop Equipment",
  "51": "Hand Tools",
  "52": "Measuring Tools",
  "53": "Hardware and Abrasives",
  "54": "Prefabricated Structures and Scaffolding",
  "55": "Lumber, Millwork, Plywood, and Veneer",
  "56": "Construction and Building Materials",
  "58": "Communication, Detection, and Coherent Radiation Equipment",
  "59": "Electrical and Electronic Equipment Components",
  "60": "Fiber Optics Materials and Components",
  "61": "Electric Wire, Power and Distribution Equipment",
  "62": "Lighting Fixtures and Lamps",
  "63": "Alarm, Signal, and Security Detection Systems",
  "65": "Medical, Dental, and Veterinary Equipment and Supplies",
  "66": "Instruments and Laboratory Equipment",
  "67": "Photographic Equipment",
  "68": "Chemicals and Chemical Products",
  "69": "Training Aids and Devices",
  "70": "ADP Equipment, Software, Supplies, and Support Equipment",
  "71": "Furniture",
  "72": "Household and Commercial Furnishings",
  "73": "Food Preparation and Serving Equipment",
  "74": "Office Machines, Text Processing, and Visible Record Equipment",
  "75": "Office Supplies and Devices",
  "76": "Books, Maps, and Other Publications",
  "77": "Musical Instruments, Phonographs, and Home Radios",
  "78": "Recreational and Athletic Equipment",
  "79": "Cleaning Equipment and Supplies",
  "80": "Brushes, Paints, Sealers, and Adhesives",
  "81": "Containers, Packaging, and Packing Supplies",
  "83": "Textiles, Leather, Furs, Apparel, Tents, and Flags",
  "84": "Clothing, Individual Equipment, and Insignia",
  "85": "Toiletries",
  "87": "Agricultural Supplies",
  "88": "Live Animals",
  "89": "Subsistence (Food)",
  "91": "Fuels, Lubricants, Oils, and Waxes",
  "93": "Nonmetallic Fabricated Materials",
  "94": "Nonmetallic Crude Materials",
  "95": "Metal Bars, Sheets, and Shapes",
  "96": "Ores, Minerals, and Their Primary Products",
  "99": "Miscellaneous",
  // Common specific codes
  "D301": "ADP Facility Management",
  "D302": "ADP Systems Development",
  "D303": "ADP Data Entry",
  "D304": "ADP Telecom and Transmission",
  "D305": "ADP Teleprocessing and Timesharing",
  "D306": "ADP Systems Analysis",
  "D307": "Automated Information System Design and Integration",
  "D308": "Programming",
  "D309": "Information Technology Management",
  "D310": "Cyber Security and Data Backup",
  "D311": "IT Strategy and Architecture",
  "D312": "IT Business Process Reengineering",
  "D313": "Computer Aided Design/Manufacturing",
  "D314": "ADP System Acquisition Support",
  "D316": "ADP Telecommunications Network Management",
  "D317": "Web-Based Subscription",
  "D318": "IT Modernization",
  "D319": "IT Data Analysis",
  "D399": "Other ADP and Telecom Services",
  "R408": "Program Management/Support",
  "R425": "Engineering and Technical Services",
  "R499": "Other Professional Services",
  "R699": "Other Administrative Support Services",
  "R706": "Logistics Support Services",
  "R707": "Mail Management Services",
  "R799": "Other Management Support Services",
};

export function naicsDescription(code: string | null | undefined): string | null {
  if (!code) return null;
  return NAICS[code] ?? null;
}

export function pscDescription(code: string | null | undefined): string | null {
  if (!code) return null;
  // Try exact match first, then 2-char prefix
  return PSC[code] ?? PSC[code.slice(0, 2)] ?? PSC[code.charAt(0)] ?? null;
}
